"""remove SimpleTitle table; Post.simple_title now a string

Revision ID: 3ef80e9d85cc
Revises: 6208a986e16e
Create Date: 2019-03-07 05:03:44.944140

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3ef80e9d85cc'
down_revision = '6208a986e16e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('simple_title', sa.String(length=100), nullable=True))
    op.create_index(op.f('ix_post_simple_title'), 'post', ['simple_title'], unique=True)
    op.drop_index('ix_simple_title_text', table_name='simple_title')
    op.create_index(op.f('ix_simple_title_text'), 'simple_title', ['text'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_simple_title_text'), table_name='simple_title')
    op.create_index('ix_simple_title_text', 'simple_title', ['text'], unique=False)
    op.drop_index(op.f('ix_post_simple_title'), table_name='post')
    op.drop_column('post', 'simple_title')
    # ### end Alembic commands ###
