"""make Tag.text unique

Revision ID: 55e090119865
Revises: a7ac3bea0cd4
Create Date: 2019-03-07 06:54:17.652408

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '55e090119865'
down_revision = 'a7ac3bea0cd4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_tag_text', table_name='tag')
    op.create_index(op.f('ix_tag_text'), 'tag', ['text'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tag_text'), table_name='tag')
    op.create_index('ix_tag_text', 'tag', ['text'], unique=False)
    # ### end Alembic commands ###
