"""add summary to Post

Revision ID: 6b082c671656
Revises: f8213d814e71
Create Date: 2019-03-17 02:41:38.361189

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b082c671656'
down_revision = 'f8213d814e71'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('summary', sa.Text(), nullable=True))
    
    # Below two lines are probably not needed anymore (added index creation to SQL script) 
    #op.create_index(op.f('ix_post_simple_title'), 'post', ['simple_title'], unique=True)
    #op.create_index(op.f('ix_post_timestamp'), 'post', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_post_timestamp'), table_name='post')
    op.drop_index(op.f('ix_post_simple_title'), table_name='post')
    op.drop_column('post', 'summary')
    # ### end Alembic commands ###
