"""user tokens

Revision ID: b96046683c36
Revises: 6b082c671656
Create Date: 2019-04-07 20:39:26.724142

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b96046683c36'
down_revision = '6b082c671656'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('token_expiration', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'token_expiration')
    # ### end Alembic commands ###
