"""add index=True to SimpleTitle.text

Revision ID: bcdebdb439fe
Revises: 725a487f3f48
Create Date: 2019-03-05 07:22:57.121823

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bcdebdb439fe'
down_revision = '725a487f3f48'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_simple_title_text'), 'simple_title', ['text'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_simple_title_text'), table_name='simple_title')
    # ### end Alembic commands ###
