"""remove body column from Post

Revision ID: f8213d814e71
Revises: 55e090119865
Create Date: 2019-03-17 00:54:35.791148

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f8213d814e71'
down_revision = '55e090119865'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'body')
    # Comment out the above line if using SQLite (it doesn't support dropping columns)
    # Instead, run '.read sql_drop_post_body.sql' in SQLite, and just pass here.
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('body', sa.TEXT(), nullable=True))
    # ### end Alembic commands ###
