"""public option for posts

Revision ID: f8cea27102b9
Revises: 950c494b1513
Create Date: 2019-02-26 05:29:14.288127

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f8cea27102b9'
down_revision = '950c494b1513'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('public', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'public')
    # ### end Alembic commands ###
